FROM ruby:2.6.3-alpine3.9


RUN apk add --no-cache --update build-base \
  linux-headers \
  git \
  postgresql-dev \
  nodejs \
  tzdata



ARG DATABASE_URL="postgres://postgres@db"
ARG RAILS_ENV=production


WORKDIR /pretty-little-things
COPY Gemfile /pretty-little-things/Gemfile
COPY Gemfile.lock /pretty-little-things/Gemfile.lock

RUN gem install bundler && bundle install
COPY . /pretty-little-things


COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]